FROM tomcat:8.5.11
MAINTAINER inghackathon2017
ENV LANG=C.UTF-8 LANGUAGE=C LC_ALL=C.UTF-8 TERM=linux
# Debug/monitoring utils
RUN \
 apt-get update &&\
 apt-get upgrade --yes &&\
 apt-get install --yes bash curl git vim less htop telnet net-tools nano mc && \
 apt-get clean