spring:
  datasource:
    platform:
    url: jdbc:postgresql://postgres:5432/obp
    username: postgres
    password: h4ck4th0n2017ingpl
    sql-script-encoding: utf-8
  jpa:
    hibernate:
       ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc.favicon.enabled: false
server:
  context-path: /
  port: 8080