version: '2'
services:
  OBP-API:
    image: zhpregistry-on.azurecr.io/openbankproject/obp
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/envs:/var/envs
    links:
    - postgres:postgres
    ports:
    - 80:80/tcp
    labels:
      io.rancher.container.pull_image: always
  postgres:
    image: zhpregistry-on.azurecr.io/openbankproject/postgres
    environment:
      POSTGRES_DB: obp
      POSTGRES_PASSWORD: h4ck4th0n2017ingpl
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /data/postgres:/var/lib/postgresql/data
    - /var/envs:/var/envs
    ports:
    - 5432:5432/tcp
    labels:
      io.rancher.container.pull_image: always