UPDATE mappedcustomer SET mrelationshipstatus='divorced' WHERE mrelationshipstatus='rozwiedziona';
UPDATE mappedcustomer SET mrelationshipstatus='divorced' WHERE mrelationshipstatus='rozwiedziony';
UPDATE mappedcustomer SET mrelationshipstatus='married' WHERE mrelationshipstatus='mężatka';
UPDATE mappedcustomer SET mrelationshipstatus='married' WHERE mrelationshipstatus='żonaty';
UPDATE mappedcustomer SET mrelationshipstatus='single' WHERE mrelationshipstatus='kawaler';
UPDATE mappedcustomer SET mrelationshipstatus='single' WHERE mrelationshipstatus='panna';
UPDATE mappedcustomer SET mrelationshipstatus='widow' WHERE mrelationshipstatus='wdowa';
UPDATE mappedcustomer SET mrelationshipstatus='widower' WHERE mrelationshipstatus='wdowiec';

UPDATE mappedcustomer SET mhighesteducationattained='bachelor ' WHERE mhighesteducationattained='zasadnicze';
UPDATE mappedcustomer SET mhighesteducationattained='doctoral' WHERE mhighesteducationattained='wyższe';
UPDATE mappedcustomer SET mhighesteducationattained='master' WHERE mhighesteducationattained='średnie';

UPDATE mappedcustomer SET memploymentstatus='contract for an indefinite period' WHERE memploymentstatus='umowa na czas nieokreślony';
UPDATE mappedcustomer SET memploymentstatus='contract work' WHERE memploymentstatus='umowa o dzieło';
UPDATE mappedcustomer SET memploymentstatus='trial contract' WHERE memploymentstatus='umowa na okres próbny';

UPDATE mappedtransaction SET description='1kg enriched uranium' WHERE description='Kilo wzbogaconego Uranu';
UPDATE mappedtransaction SET description='Agreement no 1152/2195' WHERE description='Umowa nr 1152/2195';
UPDATE mappedtransaction SET description='Agreement no 1232/1058' WHERE description='Umowa nr 1232/1058';
UPDATE mappedtransaction SET description='Agreement no 1291/2003' WHERE description='Umowa nr 1291/2003';
UPDATE mappedtransaction SET description='Agreement no 1415/2399' WHERE description='Umowa nr 1415/2399';
UPDATE mappedtransaction SET description='Agreement no 1471/986' WHERE description='Umowa nr 1471/986';
UPDATE mappedtransaction SET description='Agreement no 1521/1999' WHERE description='Umowa nr 1521/1999';
UPDATE mappedtransaction SET description='Agreement no 1618/208' WHERE description='Umowa nr 1618/208';
UPDATE mappedtransaction SET description='Agreement no 1656/912' WHERE description='Umowa nr 1656/912';
UPDATE mappedtransaction SET description='Agreement no 2138/593' WHERE description='Umowa nr 2138/593';
UPDATE mappedtransaction SET description='Agreement no 2214/218' WHERE description='Umowa nr 2214/218';
UPDATE mappedtransaction SET description='Agreement no 2297/420' WHERE description='Umowa nr 2297/420';
UPDATE mappedtransaction SET description='Agreement no 2312/654' WHERE description='Umowa nr 2312/654';
UPDATE mappedtransaction SET description='Agreement no 2314/1079' WHERE description='Umowa nr 2314/1079';
UPDATE mappedtransaction SET description='Agreement no 2342/1997' WHERE description='Umowa nr 2342/1997';
UPDATE mappedtransaction SET description='Agreement no 2459/313' WHERE description='Umowa nr 2459/313';
UPDATE mappedtransaction SET description='Agreement no 283/1074' WHERE description='Umowa nr 283/1074';
UPDATE mappedtransaction SET description='Agreement no 287/1988' WHERE description='Umowa nr 287/1988';
UPDATE mappedtransaction SET description='Agreement no 460/761' WHERE description='Umowa nr 460/761';
UPDATE mappedtransaction SET description='Agreement no 471/2004' WHERE description='Umowa nr 471/2004';
UPDATE mappedtransaction SET description='Agreement no 593/2480' WHERE description='Umowa nr 593/2480';
UPDATE mappedtransaction SET description='Agreement no 718/2219' WHERE description='Umowa nr 718/2219';
UPDATE mappedtransaction SET description='Agreement no 739/675' WHERE description='Umowa nr 739/675';
UPDATE mappedtransaction SET description='Agreement no 886/2339' WHERE description='Umowa nr 886/2339';
UPDATE mappedtransaction SET description='Agreement no 931/2443' WHERE description='Umowa nr 931/2443';
UPDATE mappedtransaction SET description='Apart shopping.' WHERE description='Apart zakupy.';
UPDATE mappedtransaction SET description='Apteka Melissa shopping.' WHERE description='Apteka Melissa zakupy.';
UPDATE mappedtransaction SET description='Barber service' WHERE description='Usługa fryzjerska';
UPDATE mappedtransaction SET description='Beer' WHERE description='Piwo';
UPDATE mappedtransaction SET description='Biedronka shopping.' WHERE description='Biedronka zakupy.';
UPDATE mappedtransaction SET description='Birthday cheap in' WHERE description='Składka na urodziny';
UPDATE mappedtransaction SET description='Blue Moon, Colombian, 4kg.' WHERE description='Blue Moon, kolumbijska, 4kg.';
UPDATE mappedtransaction SET description='books eMpik' WHERE description='Ksiązki w eMpik';
UPDATE mappedtransaction SET description='Bread' WHERE description='Pieczywo';
UPDATE mappedtransaction SET description='Breakfast' WHERE description='Śniadanie';
UPDATE mappedtransaction SET description='Brunch' WHERE description='Obiad w pracy';
UPDATE mappedtransaction SET description='Cefarm25 shopping.' WHERE description='Cefarm25 zakupy.';
UPDATE mappedtransaction SET description='Childcare' WHERE description='Opieka nad dziećmi';
UPDATE mappedtransaction SET description='Cinema City shopping.' WHERE description='Cinema City zakupy.';
UPDATE mappedtransaction SET description='Cinema' WHERE description='Kino';
UPDATE mappedtransaction SET description='Coffee ' WHERE description='Kawa';
UPDATE mappedtransaction SET description='Contraceptive pills' WHERE description='Globulki';
UPDATE mappedtransaction SET description='Contract of employment 01/2016' WHERE description='Umowa o pracę 01/2016';
UPDATE mappedtransaction SET description='Contract of employment 01/2017' WHERE description='Umowa o pracę 01/2017';
UPDATE mappedtransaction SET description='Contract of employment 02/2016' WHERE description='Umowa o pracę 02/2016';
UPDATE mappedtransaction SET description='Contract of employment 02/2017' WHERE description='Umowa o pracę 02/2017';
UPDATE mappedtransaction SET description='Contract of employment 03/2016' WHERE description='Umowa o pracę 03/2016';
UPDATE mappedtransaction SET description='Contract of employment 03/2017' WHERE description='Umowa o pracę 03/2017';
UPDATE mappedtransaction SET description='Contract of employment 04/2016' WHERE description='Umowa o pracę 04/2016';
UPDATE mappedtransaction SET description='Contract of employment 04/2017' WHERE description='Umowa o pracę 04/2017';
UPDATE mappedtransaction SET description='Contract of employment 05/2015' WHERE description='Umowa o pracę 05/2015';
UPDATE mappedtransaction SET description='Contract of employment 05/2016' WHERE description='Umowa o pracę 05/2016';
UPDATE mappedtransaction SET description='Contract of employment 05/2017' WHERE description='Umowa o pracę 05/2017';
UPDATE mappedtransaction SET description='Contract of employment 06/2015' WHERE description='Umowa o pracę 06/2015';
UPDATE mappedtransaction SET description='Contract of employment 06/2016' WHERE description='Umowa o pracę 06/2016';
UPDATE mappedtransaction SET description='Contract of employment 07/2015' WHERE description='Umowa o pracę 07/2015';
UPDATE mappedtransaction SET description='Contract of employment 07/2016' WHERE description='Umowa o pracę 07/2016';
UPDATE mappedtransaction SET description='Contract of employment 08/2015' WHERE description='Umowa o pracę 08/2015';
UPDATE mappedtransaction SET description='Contract of employment 08/2016' WHERE description='Umowa o pracę 08/2016';
UPDATE mappedtransaction SET description='Contract of employment 09/2015' WHERE description='Umowa o pracę 09/2015';
UPDATE mappedtransaction SET description='Contract of employment 09/2016' WHERE description='Umowa o pracę 09/2016';
UPDATE mappedtransaction SET description='Contract of employment 10/2015' WHERE description='Umowa o pracę 10/2015';
UPDATE mappedtransaction SET description='Contract of employment 10/2016' WHERE description='Umowa o pracę 10/2016';
UPDATE mappedtransaction SET description='Contract of employment 11/2015' WHERE description='Umowa o pracę 11/2015';
UPDATE mappedtransaction SET description='Contract of employment 11/2016' WHERE description='Umowa o pracę 11/2016';
UPDATE mappedtransaction SET description='Contract of employment 12/2015' WHERE description='Umowa o pracę 12/2015';
UPDATE mappedtransaction SET description='Contract of employment 12/2016' WHERE description='Umowa o pracę 12/2016';
UPDATE mappedtransaction SET description='Cough syrup' WHERE description='Syrop na kaszel';
UPDATE mappedtransaction SET description='Courier package' WHERE description='Kurier paczka';
UPDATE mappedtransaction SET description='Credit' WHERE description='Kredyt';
UPDATE mappedtransaction SET description='Danke!' WHERE description='Dzięki!';
UPDATE mappedtransaction SET description='Diapers for Adaśko' WHERE description='Pieluchy dla Adasia';
UPDATE mappedtransaction SET description='Dinner' WHERE description='Obiad';
UPDATE mappedtransaction SET description='Division of bills' WHERE description='Podział rachunków';
UPDATE mappedtransaction SET description='Douglas shopping.' WHERE description='Douglas zakupy.';
UPDATE mappedtransaction SET description='Dron' WHERE description='Dron';
UPDATE mappedtransaction SET description='Dryer purchase' WHERE description='Zakup suszarki';
UPDATE mappedtransaction SET description='E-Fryzjer shopping.' WHERE description='E-Fryzjer zakupy.';
UPDATE mappedtransaction SET description='Electricity bill' WHERE description='Rachunek za prąd.';
UPDATE mappedtransaction SET description='Empik shopping.' WHERE description='Empik zakupy.';
UPDATE mappedtransaction SET description='Energy payment' WHERE description='Opłata za energię';
UPDATE mappedtransaction SET description='Error 404' WHERE description='Error 404';
UPDATE mappedtransaction SET description='ET phone home' WHERE description='ET phone home';
UPDATE mappedtransaction SET description='Extortion' WHERE description='Haracz';
UPDATE mappedtransaction SET description='Fee for additional channels' WHERE description='opłata za dodatkowe kanały';
UPDATE mappedtransaction SET description='Feet massage' WHERE description='Masaż stóp';
UPDATE mappedtransaction SET description='Film' WHERE description='Film';
UPDATE mappedtransaction SET description='For gas' WHERE description='Za gaz';
UPDATE mappedtransaction SET description='For rent' WHERE description='Na czynsz';
UPDATE mappedtransaction SET description='For rubber sheep' WHERE description='Za gumową owieczkę';
UPDATE mappedtransaction SET description='For sandwiches to work' WHERE description='Na kanapki do pracy';
UPDATE mappedtransaction SET description='Fuel payment' WHERE description='Opłata za paliwo';
UPDATE mappedtransaction SET description='Fuel' WHERE description='Paliwo';
UPDATE mappedtransaction SET description='Fuel' WHERE description='Za paliwo';
UPDATE mappedtransaction SET description='Gas payment 01/2016' WHERE description='Opłata za gas 01/2016';
UPDATE mappedtransaction SET description='Gas payment 01/2016' WHERE description='Opłata za gaz 01/2016';
UPDATE mappedtransaction SET description='Gas payment 01/2017' WHERE description='Opłata za gas 01/2017';
UPDATE mappedtransaction SET description='Gas payment 01/2017' WHERE description='Opłata za gaz 01/2017';
UPDATE mappedtransaction SET description='Gas payment 02/2016' WHERE description='Opłata za gas 02/2016';
UPDATE mappedtransaction SET description='Gas payment 02/2016' WHERE description='Opłata za gaz 02/2016';
UPDATE mappedtransaction SET description='Gas payment 02/2017' WHERE description='Opłata za gas 02/2017';
UPDATE mappedtransaction SET description='Gas payment 02/2017' WHERE description='Opłata za gaz 02/2017';
UPDATE mappedtransaction SET description='Gas payment 03/2016' WHERE description='Opłata za gas 03/2016';
UPDATE mappedtransaction SET description='Gas payment 03/2016' WHERE description='Opłata za gaz 03/2016';
UPDATE mappedtransaction SET description='Gas payment 03/2017' WHERE description='Opłata za gas 03/2017';
UPDATE mappedtransaction SET description='Gas payment 03/2017' WHERE description='Opłata za gaz 03/2017';
UPDATE mappedtransaction SET description='Gas payment 04/2016' WHERE description='Opłata za gas 04/2016';
UPDATE mappedtransaction SET description='Gas payment 04/2016' WHERE description='Opłata za gaz 04/2016';
UPDATE mappedtransaction SET description='Gas payment 04/2017' WHERE description='Opłata za gas 04/2017';
UPDATE mappedtransaction SET description='Gas payment 04/2017' WHERE description='Opłata za gaz 04/2017';
UPDATE mappedtransaction SET description='Gas payment 05/2015' WHERE description='Opłata za gas 05/2015';
UPDATE mappedtransaction SET description='Gas payment 05/2015' WHERE description='Opłata za gaz 05/2015';
UPDATE mappedtransaction SET description='Gas payment 05/2016' WHERE description='Opłata za gas 05/2016';
UPDATE mappedtransaction SET description='Gas payment 05/2016' WHERE description='Opłata za gaz 05/2016';
UPDATE mappedtransaction SET description='Gas payment 05/2017' WHERE description='Opłata za gas 05/2017';
UPDATE mappedtransaction SET description='Gas payment 05/2017' WHERE description='Opłata za gaz 05/2017';
UPDATE mappedtransaction SET description='Gas payment 06/2015' WHERE description='Opłata za gas 06/2015';
UPDATE mappedtransaction SET description='Gas payment 06/2015' WHERE description='Opłata za gaz 06/2015';
UPDATE mappedtransaction SET description='Gas payment 06/2016' WHERE description='Opłata za gas 06/2016';
UPDATE mappedtransaction SET description='Gas payment 06/2016' WHERE description='Opłata za gaz 06/2016';
UPDATE mappedtransaction SET description='Gas payment 07/2015' WHERE description='Opłata za gas 07/2015';
UPDATE mappedtransaction SET description='Gas payment 07/2015' WHERE description='Opłata za gaz 07/2015';
UPDATE mappedtransaction SET description='Gas payment 07/2016' WHERE description='Opłata za gas 07/2016';
UPDATE mappedtransaction SET description='Gas payment 07/2016' WHERE description='Opłata za gaz 07/2016';
UPDATE mappedtransaction SET description='Gas payment 08/2015' WHERE description='Opłata za gas 08/2015';
UPDATE mappedtransaction SET description='Gas payment 08/2015' WHERE description='Opłata za gaz 08/2015';
UPDATE mappedtransaction SET description='Gas payment 08/2016' WHERE description='Opłata za gas 08/2016';
UPDATE mappedtransaction SET description='Gas payment 08/2016' WHERE description='Opłata za gaz 08/2016';
UPDATE mappedtransaction SET description='Gas payment 09/2015' WHERE description='Opłata za gas 09/2015';
UPDATE mappedtransaction SET description='Gas payment 09/2015' WHERE description='Opłata za gaz 09/2015';
UPDATE mappedtransaction SET description='Gas payment 09/2016' WHERE description='Opłata za gas 09/2016';
UPDATE mappedtransaction SET description='Gas payment 09/2016' WHERE description='Opłata za gaz 09/2016';
UPDATE mappedtransaction SET description='Gas payment 10/2015' WHERE description='Opłata za gas 10/2015';
UPDATE mappedtransaction SET description='Gas payment 10/2015' WHERE description='Opłata za gaz 10/2015';
UPDATE mappedtransaction SET description='Gas payment 10/2016' WHERE description='Opłata za gas 10/2016';
UPDATE mappedtransaction SET description='Gas payment 10/2016' WHERE description='Opłata za gaz 10/2016';
UPDATE mappedtransaction SET description='Gas payment 11/2015' WHERE description='Opłata za gas 11/2015';
UPDATE mappedtransaction SET description='Gas payment 11/2015' WHERE description='Opłata za gaz 11/2015';
UPDATE mappedtransaction SET description='Gas payment 11/2016' WHERE description='Opłata za gas 11/2016';
UPDATE mappedtransaction SET description='Gas payment 11/2016' WHERE description='Opłata za gaz 11/2016';
UPDATE mappedtransaction SET description='Gas payment 12/2015' WHERE description='Opłata za gas 12/2015';
UPDATE mappedtransaction SET description='Gas payment 12/2015' WHERE description='Opłata za gaz 12/2015';
UPDATE mappedtransaction SET description='Gas payment 12/2016' WHERE description='Opłata za gas 12/2016';
UPDATE mappedtransaction SET description='Gas payment 12/2016' WHERE description='Opłata za gaz 12/2016';
UPDATE mappedtransaction SET description='Gas station' WHERE description='Stacja paliw';
UPDATE mappedtransaction SET description='Gas' WHERE description='Gaz';
UPDATE mappedtransaction SET description='Gift' WHERE description='Prezent';
UPDATE mappedtransaction SET description='Hand cream' WHERE description='Krem do rąk';
UPDATE mappedtransaction SET description='Headphones' WHERE description='Słuchawki';
UPDATE mappedtransaction SET description='Hot-dog' WHERE description='Hot-dog';
UPDATE mappedtransaction SET description='Hotel' WHERE description='Za hotel';
UPDATE mappedtransaction SET description='I am Spartacus.' WHERE description='I am Spartacus.';
UPDATE mappedtransaction SET description='Installment for the apartment' WHERE description='Rata za mieszkanie';
UPDATE mappedtransaction SET description='Jewelry' WHERE description='Biżuteria';
UPDATE mappedtransaction SET description='Just bury her well' WHERE description='Tylko dobrze ją zakopcie';
UPDATE mappedtransaction SET description='Kyoto Sushi shopping.' WHERE description='Kyoto Sushi zakupy.';
UPDATE mappedtransaction SET description='Laptop' WHERE description='Laptop';
UPDATE mappedtransaction SET description='Leasing' WHERE description='Leasing';
UPDATE mappedtransaction SET description='Loan installment payment' WHERE description='Spłata raty kredytu';
UPDATE mappedtransaction SET description='Loan installment' WHERE description='Rata kredytu';
UPDATE mappedtransaction SET description='May the force be with You' WHERE description='May the force be with You';
UPDATE mappedtransaction SET description='Mediamarkt.pl shopping.' WHERE description='Mediamarkt.pl zakupy.';
UPDATE mappedtransaction SET description='Monthly rent 01/2016' WHERE description='Czynsz za miesiąc 01/2016';
UPDATE mappedtransaction SET description='Monthly rent 01/2017' WHERE description='Czynsz za miesiąc 01/2017';
UPDATE mappedtransaction SET description='Monthly rent 02/2016' WHERE description='Czynsz za miesiąc 02/2016';
UPDATE mappedtransaction SET description='Monthly rent 02/2017' WHERE description='Czynsz za miesiąc 02/2017';
UPDATE mappedtransaction SET description='Monthly rent 03/2016' WHERE description='Czynsz za miesiąc 03/2016';
UPDATE mappedtransaction SET description='Monthly rent 03/2017' WHERE description='Czynsz za miesiąc 03/2017';
UPDATE mappedtransaction SET description='Monthly rent 04/2016' WHERE description='Czynsz za miesiąc 04/2016';
UPDATE mappedtransaction SET description='Monthly rent 04/2017' WHERE description='Czynsz za miesiąc 04/2017';
UPDATE mappedtransaction SET description='Monthly rent 05/2015' WHERE description='Czynsz za miesiąc 05/2015';
UPDATE mappedtransaction SET description='Monthly rent 05/2016' WHERE description='Czynsz za miesiąc 05/2016';
UPDATE mappedtransaction SET description='Monthly rent 05/2017' WHERE description='Czynsz za miesiąc 05/2017';
UPDATE mappedtransaction SET description='Monthly rent 06/2015' WHERE description='Czynsz za miesiąc 06/2015';
UPDATE mappedtransaction SET description='Monthly rent 06/2016' WHERE description='Czynsz za miesiąc 06/2016';
UPDATE mappedtransaction SET description='Monthly rent 07/2015' WHERE description='Czynsz za miesiąc 07/2015';
UPDATE mappedtransaction SET description='Monthly rent 07/2016' WHERE description='Czynsz za miesiąc 07/2016';
UPDATE mappedtransaction SET description='Monthly rent 08/2015' WHERE description='Czynsz za miesiąc 08/2015';
UPDATE mappedtransaction SET description='Monthly rent 08/2016' WHERE description='Czynsz za miesiąc 08/2016';
UPDATE mappedtransaction SET description='Monthly rent 09/2015' WHERE description='Czynsz za miesiąc 09/2015';
UPDATE mappedtransaction SET description='Monthly rent 09/2016' WHERE description='Czynsz za miesiąc 09/2016';
UPDATE mappedtransaction SET description='Monthly rent 10/2015' WHERE description='Czynsz za miesiąc 10/2015';
UPDATE mappedtransaction SET description='Monthly rent 10/2016' WHERE description='Czynsz za miesiąc 10/2016';
UPDATE mappedtransaction SET description='Monthly rent 11/2015' WHERE description='Czynsz za miesiąc 11/2015';
UPDATE mappedtransaction SET description='Monthly rent 11/2016' WHERE description='Czynsz za miesiąc 11/2016';
UPDATE mappedtransaction SET description='Monthly rent 12/2015' WHERE description='Czynsz za miesiąc 12/2015';
UPDATE mappedtransaction SET description='Monthly rent 12/2016' WHERE description='Czynsz za miesiąc 12/2016';
UPDATE mappedtransaction SET description='Mortgage' WHERE description='Rata na dom';
UPDATE mappedtransaction SET description='Offset the bypass for a few kilometers, because the view from the gazebo broke' WHERE description='Za przesunięcie obwodnicy o parę kilometrów, bo widok z altanki psuła';
UPDATE mappedtransaction SET description='Phone' WHERE description='Na telefon';
UPDATE mappedtransaction SET description='Popcorn and Coke' WHERE description='Popcorn i Cola';
UPDATE mappedtransaction SET description='Printer' WHERE description='Drukarka';
UPDATE mappedtransaction SET description='Refund for a taxi' WHERE description='Zwrot za taxi';
UPDATE mappedtransaction SET description='Refund for AGD' WHERE description='Zwrot za AGD';
UPDATE mappedtransaction SET description='Reimbursement' WHERE description='Zwrot kosztów';
UPDATE mappedtransaction SET description='Rent for a box no 9' WHERE description='Czynsz za karton nr 9';
UPDATE mappedtransaction SET description='Rent' WHERE description='Czynsz';
UPDATE mappedtransaction SET description='Restauracja Złoty Osioł dinner.' WHERE description='Restauracja Złoty Osioł zakupy.';
UPDATE mappedtransaction SET description='Salary 01/2016' WHERE description='Salary 01/2016';
UPDATE mappedtransaction SET description='Salary 01/2016' WHERE description='Wypłata 01/2016';
UPDATE mappedtransaction SET description='Salary 01/2017' WHERE description='Salary 01/2017';
UPDATE mappedtransaction SET description='Salary 01/2017' WHERE description='Wypłata 01/2017';
UPDATE mappedtransaction SET description='Salary 02/2016' WHERE description='Salary 02/2016';
UPDATE mappedtransaction SET description='Salary 02/2016' WHERE description='Wypłata 02/2016';
UPDATE mappedtransaction SET description='Salary 02/2017' WHERE description='Salary 02/2017';
UPDATE mappedtransaction SET description='Salary 02/2017' WHERE description='Wypłata 02/2017';
UPDATE mappedtransaction SET description='Salary 03/2016' WHERE description='Salary 03/2016';
UPDATE mappedtransaction SET description='Salary 03/2016' WHERE description='Wypłata 03/2016';
UPDATE mappedtransaction SET description='Salary 03/2017' WHERE description='Salary 03/2017';
UPDATE mappedtransaction SET description='Salary 03/2017' WHERE description='Wypłata 03/2017';
UPDATE mappedtransaction SET description='Salary 04/2016' WHERE description='Salary 04/2016';
UPDATE mappedtransaction SET description='Salary 04/2016' WHERE description='Wypłata 04/2016';
UPDATE mappedtransaction SET description='Salary 04/2017' WHERE description='Salary 04/2017';
UPDATE mappedtransaction SET description='Salary 04/2017' WHERE description='Wypłata 04/2017';
UPDATE mappedtransaction SET description='Salary 05/2015' WHERE description='Salary 05/2015';
UPDATE mappedtransaction SET description='Salary 05/2015' WHERE description='Wypłata 05/2015';
UPDATE mappedtransaction SET description='Salary 05/2016' WHERE description='Salary 05/2016';
UPDATE mappedtransaction SET description='Salary 05/2016' WHERE description='Wypłata 05/2016';
UPDATE mappedtransaction SET description='Salary 05/2017' WHERE description='Salary 05/2017';
UPDATE mappedtransaction SET description='Salary 05/2017' WHERE description='Wypłata 05/2017';
UPDATE mappedtransaction SET description='Salary 06/2015' WHERE description='Salary 06/2015';
UPDATE mappedtransaction SET description='Salary 06/2015' WHERE description='Wypłata 06/2015';
UPDATE mappedtransaction SET description='Salary 06/2016' WHERE description='Salary 06/2016';
UPDATE mappedtransaction SET description='Salary 06/2016' WHERE description='Wypłata 06/2016';
UPDATE mappedtransaction SET description='Salary 07/2015' WHERE description='Salary 07/2015';
UPDATE mappedtransaction SET description='Salary 07/2015' WHERE description='Wypłata 07/2015';
UPDATE mappedtransaction SET description='Salary 07/2016' WHERE description='Salary 07/2016';
UPDATE mappedtransaction SET description='Salary 07/2016' WHERE description='Wypłata 07/2016';
UPDATE mappedtransaction SET description='Salary 08/2015' WHERE description='Salary 08/2015';
UPDATE mappedtransaction SET description='Salary 08/2015' WHERE description='Wypłata 08/2015';
UPDATE mappedtransaction SET description='Salary 08/2016' WHERE description='Salary 08/2016';
UPDATE mappedtransaction SET description='Salary 08/2016' WHERE description='Wypłata 08/2016';
UPDATE mappedtransaction SET description='Salary 09/2015' WHERE description='Salary 09/2015';
UPDATE mappedtransaction SET description='Salary 09/2015' WHERE description='Wypłata 09/2015';
UPDATE mappedtransaction SET description='Salary 09/2016' WHERE description='Salary 09/2016';
UPDATE mappedtransaction SET description='Salary 09/2016' WHERE description='Wypłata 09/2016';
UPDATE mappedtransaction SET description='Salary 10/2015' WHERE description='Salary 10/2015';
UPDATE mappedtransaction SET description='Salary 10/2015' WHERE description='Wypłata 10/2015';
UPDATE mappedtransaction SET description='Salary 10/2016' WHERE description='Salary 10/2016';
UPDATE mappedtransaction SET description='Salary 10/2016' WHERE description='Wypłata 10/2016';
UPDATE mappedtransaction SET description='Salary 11/2015' WHERE description='Salary 11/2015';
UPDATE mappedtransaction SET description='Salary 11/2015' WHERE description='Wypłata 11/2015';
UPDATE mappedtransaction SET description='Salary 11/2016' WHERE description='Salary 11/2016';
UPDATE mappedtransaction SET description='Salary 11/2016' WHERE description='Wypłata 11/2016';
UPDATE mappedtransaction SET description='Salary 12/2015' WHERE description='Salary 12/2015';
UPDATE mappedtransaction SET description='Salary 12/2015' WHERE description='Wypłata 12/2015';
UPDATE mappedtransaction SET description='Salary 12/2016' WHERE description='Salary 12/2016';
UPDATE mappedtransaction SET description='Salary 12/2016' WHERE description='Wypłata 12/2016';
UPDATE mappedtransaction SET description='Saturday night fever' WHERE description='Impreza w sobotę';
UPDATE mappedtransaction SET description='Saturn shopping.' WHERE description='Saturn zakupy.';
UPDATE mappedtransaction SET description='Say hello to my little friend!' WHERE description='Say hello to my little friend!';
UPDATE mappedtransaction SET description='Shopping' WHERE description='Zakupy';
UPDATE mappedtransaction SET description='Small loan' WHERE description='Mała pożyczka';
UPDATE mappedtransaction SET description='Something funny here' WHERE description='Taki fajny przelew';
UPDATE mappedtransaction SET description='SSD drive' WHERE description='Dysk SSD';
UPDATE mappedtransaction SET description='Subscription fee for urinal using' WHERE description='Opłata abonamentowa za korzystanie z pisuaru';
UPDATE mappedtransaction SET description='Supper' WHERE description='Kolacja';
UPDATE mappedtransaction SET description='Sushi' WHERE description='Sushi';
UPDATE mappedtransaction SET description='Świat Alkoholi shopping.' WHERE description='Świat Alkoholi zakupy.';
UPDATE mappedtransaction SET description='Tailor' WHERE description='Krawiec';
UPDATE mappedtransaction SET description='Tennis' WHERE description='Tennis';
UPDATE mappedtransaction SET description='Tesco shopping' WHERE description='Zakupy w Tesco';
UPDATE mappedtransaction SET description='Thanks for lovely supper!' WHERE description='Dziękuję za kolację!';
UPDATE mappedtransaction SET description='Thursday shopping' WHERE description='Za zakupy w czwartek';
UPDATE mappedtransaction SET description='Tour' WHERE description='Wycieczka';
UPDATE mappedtransaction SET description='Transfer mom' WHERE description='Mama przelew';
UPDATE mappedtransaction SET description='Trip' WHERE description='Wyjazd';
UPDATE mappedtransaction SET description='TV' WHERE description='TV';
UPDATE mappedtransaction SET description='Underwear' WHERE description='Bielizna';
UPDATE mappedtransaction SET description='Vet - cat' WHERE description='Weterynarz - kot';
UPDATE mappedtransaction SET description='Victoria’s Secret shopping.' WHERE description='Victoria’s Secret zakupy.';
UPDATE mappedtransaction SET description='Wake up Neo!' WHERE description='Wake up Neo!';
UPDATE mappedtransaction SET description='Water 01/2016' WHERE description='Woda 01/2016';
UPDATE mappedtransaction SET description='Water 01/2017' WHERE description='Woda 01/2017';
UPDATE mappedtransaction SET description='Water 02/2016' WHERE description='Woda 02/2016';
UPDATE mappedtransaction SET description='Water 02/2017' WHERE description='Woda 02/2017';
UPDATE mappedtransaction SET description='Water 03/2016' WHERE description='Woda 03/2016';
UPDATE mappedtransaction SET description='Water 03/2017' WHERE description='Woda 03/2017';
UPDATE mappedtransaction SET description='Water 04/2016' WHERE description='Woda 04/2016';
UPDATE mappedtransaction SET description='Water 04/2017' WHERE description='Woda 04/2017';
UPDATE mappedtransaction SET description='Water 05/2015' WHERE description='Woda 05/2015';
UPDATE mappedtransaction SET description='Water 05/2016' WHERE description='Woda 05/2016';
UPDATE mappedtransaction SET description='Water 05/2017' WHERE description='Woda 05/2017';
UPDATE mappedtransaction SET description='Water 06/2015' WHERE description='Woda 06/2015';
UPDATE mappedtransaction SET description='Water 06/2016' WHERE description='Woda 06/2016';
UPDATE mappedtransaction SET description='Water 07/2015' WHERE description='Woda 07/2015';
UPDATE mappedtransaction SET description='Water 07/2016' WHERE description='Woda 07/2016';
UPDATE mappedtransaction SET description='Water 08/2015' WHERE description='Woda 08/2015';
UPDATE mappedtransaction SET description='Water 08/2016' WHERE description='Woda 08/2016';
UPDATE mappedtransaction SET description='Water 09/2015' WHERE description='Woda 09/2015';
UPDATE mappedtransaction SET description='Water 09/2016' WHERE description='Woda 09/2016';
UPDATE mappedtransaction SET description='Water 10/2015' WHERE description='Woda 10/2015';
UPDATE mappedtransaction SET description='Water 10/2016' WHERE description='Woda 10/2016';
UPDATE mappedtransaction SET description='Water 11/2015' WHERE description='Woda 11/2015';
UPDATE mappedtransaction SET description='Water 11/2016' WHERE description='Woda 11/2016';
UPDATE mappedtransaction SET description='Water 12/2015' WHERE description='Woda 12/2015';
UPDATE mappedtransaction SET description='Water 12/2016' WHERE description='Woda 12/2016';
UPDATE mappedtransaction SET description='X-Kom shopping.' WHERE description='X-Kom zakupy.';
UPDATE mappedtransaction SET description='Year bonus 2016' WHERE description='Year bonus 2016';
UPDATE mappedtransaction SET description='Year bonus 2017' WHERE description='Year bonus 2017';
UPDATE mappedtransaction SET description='Youre gonna need a bigger boat.' WHERE description='Youre gonna need a bigger boat.';
UPDATE mappedtransaction SET description='Żabka shopping.' WHERE description='Żabka zakupy.';